---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: rag3-oct18-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rag3-oct18-1 
  name: rag3-oct18-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi